steps:
  # - name: gcr.io/cloud-builders/gsutil
  #   args: ['cp', 'gs://mybucket/results.zip', 'previous_results.zip']
  # operations that use previous_results.zip and produce new_results.zip
  - name: node:12.20.1
    entrypoint: npm
    args: ['run', 'create-env']
    env:
      - 'APP_SECRET=${_APP_SECRET}'
      - 'STRAPI_AUTHENTICATED_API_KEY=${_STRAPI_AUTHENTICATED_API_KEY}'
      - 'NEXTAUTH_URL=${_NEXTAUTH_URL}'
      - 'NEXT_PUBLIC_STRAPI_API_URL=${_NEXT_PUBLIC_STRAPI_API_URL}'
      - 'NEXT_PUBLIC_GOOGLE_ANALYTICS=${_NEXT_PUBLIC_GOOGLE_ANALYTICS}'
      - 'NEXT_PUBLIC_TEST_VAR=${_NEXT_PUBLIC_TEST_VAR}'
      - 'FB_API_KEY=${_FB_API_KEY}'
      - 'FB_DATABASE_URL=${_FB_DATABASE_URL}'
      - 'FB_MESSAGING_SENDER_ID=${_FB_MESSAGING_SENDER_ID}'
      - 'FB_APP_ID=${_FB_APP_ID}'
      - 'FB_MEASUREMENT_ID=${_FB_MEASUREMENT_ID}'
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']
  # - name: gcr.io/cloud-builders/gsutil
  #   args: ['cp', 'new_results.zip', 'gs://mybucket/results.zip']
