steps:
  - name: node:12.20.1
    entrypoint: npm
    args: ['run', 'create-env']
    env:
      - 'APP_SECRET=${_APP_SECRET}'
      - 'STRAPI_AUTHENTICATED_API_KEY=${_STRAPI_AUTHENTICATED_API_KEY}'
      - 'NEXTAUTH_URL=${_NEXTAUTH_URL}'
      - 'NEXT_PUBLIC_STRAPI_API_URL=${_NEXT_PUBLIC_STRAPI_API_URL}'
      - 'NEXT_PUBLIC_GOOGLE_ANALYTICS=${_NEXT_PUBLIC_GOOGLE_ANALYTICS}'
      - 'NEXT_PUBLIC_TEST_VAR=${_NEXT_PUBLIC_TEST_VAR}'
      - 'FB_API_KEY=${FB_API_KEY}'
      - 'FB_DATABASE_URL=${FB_DATABASE_URL}'
      - 'FB_MESSAGING_SENDER_ID=${FB_MESSAGING_SENDER_ID}'
      - 'FB_APP_ID=${FB_APP_ID}'
      - 'FB_MEASUREMENT_ID=${FB_MEASUREMENT_ID=G}'
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']
